### ISSUE TITLE
error in market_data.subscribe / __handle_feed_event (TypeError: string indices must be integers)

### ISSUE THREAD

**Issue by cedarburgqt** [tastytrade/tastytrade-sdk-python#17]
Hello,

I am encountering an issue when attempting to use the sample code provided at https://tastytrade.github.io/tastytrade-sdk-python/tastytrade_sdk.html. In specific, I've taken the code provided for "Streaming Market Data" and made sure to substitute the credentials with my own. The code in question is below:

```
from tastytrade_sdk import Tastytrade

tasty = Tastytrade().login(login='trader@email.com', password='password')

# Subscribing to symbols across different instrument types
symbols = [
    'BTC/USD',
    'SPY',
    '/ESU3',
    'SPY   230630C00255000',
    './ESU3 EW2N3 230714C4310'
]

subscription = tasty.market_data.subscribe(
    symbols=symbols,
    on_quote=print,
    on_candle=print,
    on_greeks=print
)

# start streaming
subscription.open()
```

I receive the following output:

```
(c:\Projects\tastytest\.conda) PS C:\Projects\tastytest> & c:/Projects/tastytest/.conda/python.exe c:/Projects/tastytest/testfile.py
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Projects\tastytest\.conda\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Projects\tastytest\.conda\lib\site-packages\tastytrade_sdk\market_data\subscription.py", line 26, in run
    self.__activity()
  File "C:\Projects\tastytest\.conda\lib\site-packages\tastytrade_sdk\market_data\subscription.py", line 113, in __receive
    self.__handle_feed_event(event)
  File "C:\Projects\tastytest\.conda\lib\site-packages\tastytrade_sdk\market_data\subscription.py", line 118, in __handle_feed_event
    event_type = event['eventType']
TypeError: string indices must be integers
```

I am able to run the "validate" API route without issue, so I don't see this as being an authentication issue. I'm using Python 3.9 within an Anaconda environment on Windows, but also encountered this same problem running on AWS using Lambda. As far as I can tell this issue began occurring on 2024-04-25. 

I've spoken with some other members in the development community and was pointed towards the unofficial library, which seems like it has a patch applied that might address this issue: https://github.com/tastyware/tastytrade/commit/c0e24cfe55abc02f56d565f04316fb2a69b4442c

**Comment by pangyuteng** [comment]
my very superficial understanding of the problem by looking at `tastytrade_sdk/market_data/subscription.py` and inspecting the element types is that the data structure for `message['data']` likely changed, and the `subscription.py` likely needs to be updated accordingly.  more detail provided below.

--

Sample values for `message['data']` https://github.com/tastytrade/tastytrade-sdk-python/blob/master/src/tastytrade_sdk/market_data/subscription.py#L112
is provided below:

sample 1:
```
['Quote', ['Quote', 'SPX', 0, 0, 0, 0, '', 5646.29, 'NaN', 0, '', 5756.67, 'NaN', 'Quote', 'SPY', 0, 0, 0, 0, 'Q', 567.7, 'NaN', 0, 'Q', 568.25, 'NaN']]
```

sample 2:
```
['Candle', ['Candle', 'SPY', 0, 0, 7416879298617405007, 1726876781000, 650831, 1, 568.15, 568.15, 568.15, 568.15, 253.0, 'NaN', 'NaN', 'NaN', 'NaN', 'NaN']]
```

sample 3:
```
['Quote', ['Quote', 'BTC/USD:CXTALP', 0, 0, 0, 0, 'Z', 63076.32, 4.0, 0, 'Z', 63500.0, 0.19370079]]
```

Give above 3 samples,  below [code block](https://github.com/tastytrade/tastytrade-sdk-python/blob/7d60e7c1aaf5d83035161c6fd1ce1672e0e19c4f/src/tastytrade_sdk/market_data/subscription.py#L112) no longer makes sense:

```
            for event in message['data']:
                self.__handle_feed_event(event)
```

since both first (str) and second (list of str,int,float) element type is not `dict`.

**Comment by pangyuteng** [comment]
for those visitiing this issue and wondering what the returned values means...

Since [`src/tastytrade_sdk/market_data/subscription.py#L84`](https://github.com/tastytrade/tastytrade-sdk-python/blob/7d60e7c1aaf5d83035161c6fd1ce1672e0e19c4f/src/tastytrade_sdk/market_data/subscription.py#L84) did not call `self.__send('FEED_SETUP'...` to configure the feed, DXLinkFeed (returns all fields)[https://github.com/tastytrade/tastytrade-api-js/blob/a166b3897c7a0f35c1e95208150131aaebca2e80/README.md?plain=1#L42].

The name and data type for all fields are [available here](https://github.com/dxFeed/dxLink/blob/7cf19a85db196a23a70f6212ca1e5922e07f25e1/dxlink-specification/asyncapi.yml#L1457), sample data and corresponding field names for a `Candle` `eventType` also provided in below screenshot.

![image](https://github.com/user-attachments/assets/38d43755-8a42-4a99-a3ea-014d0d04ecbf)
